### ISSUE TITLE
OptiX 7.1 support - OptixPipelineCompileOptions::overrideUsesMotionBlur no longer exists

### ISSUE THREAD

**Issue by moddyz** [ingowald/optix7course#3]
Hi!

I've installed the latest OptiX 7.1 - building the code in this project was mostly smooth!
The only hiccup was that the member `OptixPipelineCompileOptions::overrideUsesMotionBlur` no longer exists.

I realize that the README recommended OptiX 7.0 - but figured I'd raise this as an issue because 7.1 is out now.

Thanks for these examples - and for the excellent course on Siggraph 2020!

Cheers
Richard

**Comment by ingowald** [comment]
Thanks for reminding me on this - I had actually thought it had been changed long since, but apparently I had confused this with the port from 6.5 to 7.0, so it did indeed not compile on 7.1. I have just fixed the code; it does not compile. Not having a windows machine at hand right now I haven't tested; but since changes were absolutely minimal it _should_ work.

Again, thanks for the reminder! (and glad you enjoyed the course! :-) )
