### ISSUE TITLE
Visual Studio: File Modification Detected

### ISSUE THREAD

**Issue by kyamant** [ingowald/optix7course#7]
After building and running an example in Visual Studio 2019 (debug)
_File Modification Detected
The project 'XYZ' has been modified outside the environment
..._
message is displayed. 
Encountered this with the first three examples and not tested any further with the other examples.

**Comment by ingowald** [comment]
That is not actually an error; like many other projects this project uses cmake to create the visual studio configuration, and from time to time will automagically update the VS config files, and when visual studio is open it detect that these got changed, and wants to reload it (as it should). That is expected behavior with cmake, and not an error; just accept the reload, and everything is as it should be.
